<!DOCTYPE html>
<html>
<head>
<title>Titel</title>
<link rel="stylesheet" href="/css/default.css" type="text/css" media="all">
</head>

<body>

    <div id="mainWrapper">
        <header>
            <h1>Header logo</h1>
            <nav>
                <h2>Nav</h2>
            </nav>
        </header>
        
        <section>
            <article>
                <h2>Content</h2>
            </article>
        </section>
        
        <aside>
            <h2>Sidebar</h2>
        </aside>
        
        <footer>
            <h2>Footer</h2>
        </footer>
    </div>
    
</body>

</html>