<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Combi webmaster-expert</title>
<link href="/css/default.css" rel="stylesheet" type="text/css" />
</head>

<body>
    
    <div id="mainWrapper">
        <header>
            <h1>Combi oefening</h1>
            <nav>
                <h2>Nav</h2>
                <?php echo $this->navigation()->menu(); ?>
            </nav>
        </header>
        
        <section>
            <h2>Section titel</h2>
            <article>
                <p><?php echo $this->layout()->content; ?></p>
            </article>
        </section>

        <section id="sidebar">
            <h2>Sidebar</h2>
            <p>sidebar content</p>
        </section>
        
        <footer>
            <h2>Footer</h2>
        </footer>
    </div>    

</body>
</html>